name: publish

on:
  pull_request:
    branches:
      - master
    types:
      - closed  


jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mathisburger
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/mathisburger/simpleinventory:latest